version: "3.7"

services:
  backend:
    image: bandbeat-back
    build: ./backend
    container_name: bandbeat-back
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: "database"
    ports:
      - 3000:3000
    networks:
      - bandbeat-network

  frontend:
    container_name: bandbeat-front
    image: bandbeat-front
    build:
      context: ./frontend
    restart: "no"
    ports:
      - 4200:4200
    networks:
      - bandbeat-network

  database:
    image: mongo:4.0.10-xenial
    container_name: bandbeat-database
    restart: "no"
    command:
      - --auth
      - --bind_ip_all
      - --port=27017
      - --setParameter=enableLocalhostAuthBypass=true
      - --timeStampFormat=iso8601-utc
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=alpine
    ports:
      - 27017:27017
    networks:
      - bandbeat-network

networks:
  bandbeat-network:
    name: bandbeat-network
